// src/utils/crypto.ts

const ENCODER = new TextEncoder();
const DECODER = new TextDecoder();

/**
 * Derives a 256-bit AES-GCM CryptoKey from a user password and a salt using PBKDF2.
 */
async function deriveKey(password: string, salt: Uint8Array): Promise<CryptoKey> {
  const keyMaterial = await window.crypto.subtle.importKey(
    'raw',
    ENCODER.encode(password),
    { name: 'PBKDF2' },
    false,
    ['deriveBits', 'deriveKey']
  );

  return window.crypto.subtle.deriveKey(
    {
      name: 'PBKDF2',
      salt,
      iterations: 100000,
      hash: 'SHA-256'
    },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt']
  );
}

/**
 * Encrypts a plaintext string using a password.
 * Returns a Base64 encoded string containing: base64(salt + iv + ciphertext)
 */
export async function encryptText(plaintext: string, password: string): Promise<string> {
  const salt = window.crypto.getRandomValues(new Uint8Array(16));
  const iv = window.crypto.getRandomValues(new Uint8Array(12));
  const key = await deriveKey(password, salt);

  const ciphertextBuffer = await window.crypto.subtle.encrypt(
    {
      name: 'AES-GCM',
      iv
    },
    key,
    ENCODER.encode(plaintext)
  );

  // Combine salt + iv + ciphertext into a single buffer
  const ciphertextArray = new Uint8Array(ciphertextBuffer);
  const combined = new Uint8Array(salt.length + iv.length + ciphertextArray.length);
  combined.set(salt, 0);
  combined.set(iv, salt.length);
  combined.set(ciphertextArray, salt.length + iv.length);

  // Convert to Base64
  // We use btoa with String.fromCharCode to handle binary data
  let binary = '';
  const len = combined.byteLength;
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(combined[i]);
  }
  return btoa(binary);
}

/**
 * Decrypts a Base64 encoded string generated by encryptText using a password.
 * Returns the original plaintext string.
 */
export async function decryptText(encryptedBase64: string, password: string): Promise<string> {
  try {
    const binaryStr = atob(encryptedBase64);
    const combined = new Uint8Array(binaryStr.length);
    for (let i = 0; i < binaryStr.length; i++) {
      combined[i] = binaryStr.charCodeAt(i);
    }

    // Extract salt, iv, and ciphertext
    const salt = combined.slice(0, 16);
    const iv = combined.slice(16, 16 + 12);
    const ciphertext = combined.slice(16 + 12);

    const key = await deriveKey(password, salt);

    const decryptedBuffer = await window.crypto.subtle.decrypt(
      {
        name: 'AES-GCM',
        iv
      },
      key,
      ciphertext
    );

    return DECODER.decode(decryptedBuffer);
  } catch (error) {
    throw new Error('Decryption failed. Incorrect password or corrupted data.');
  }
}
